name: AI Code Review Inline (Ollama)

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get PR diff with line numbers
      run: |
        git fetch origin ${{ github.base_ref }}
        git diff --unified=0 origin/${{ github.base_ref }}...HEAD > pr_diff.txt
        echo "=== DIFF ==="
        cat pr_diff.txt

    - name: Install Ollama
      run: |
        curl -fsSL https://ollama.com/install.sh | sh
        ollama serve & sleep 5

    - name: Pull LLM model
      run: |
        ollama pull codellama:7b

    - name: Run AI review with JSON output
      run: |
        DIFF_CONTENT=$(cat pr_diff.txt | head -c 4000)
        PROMPT="You are a senior software engineer reviewing a GitHub Pull Request.
        Output must be in JSON array format ONLY, like this:
        [{\"file\":\"src/main/java/App.java\",\"line\":10,\"comment\":\"Consider using try-with-resources for better resource management.\"}]
        Do not include anything else besides valid JSON.
        Review this diff:\n\n$DIFF_CONTENT"

                ollama run codellama:7b "$PROMPT" > raw_review.txt
                cat raw_review.txt | jq . > review.json || echo "[]">review.json
                echo "=== AI INLINE REVIEW JSON ==="
                cat review.json

    - name: Post inline comments to PR
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          const comments = JSON.parse(fs.readFileSync('review.json', 'utf8'));
          for (const c of comments) {
            try {
              await github.rest.pulls.createReviewComment({
                owner: context.repo.owner,
                repo: context.repo.name,
                pull_number: context.payload.pull_request.number,
                body: `🤖 AI Suggestion:\n${c.comment}`,
                commit_id: context.payload.pull_request.head.sha,
                path: c.file,
                line: c.line,
                side: "RIGHT"
              });
            } catch (err) {
              console.log("Failed to comment:", err.message);
            }
          }
